### ISSUE TITLE
Automatically patch `level.dat`

### ISSUE THREAD

**Issue by Wesley-Young** [bedrock-stdhub/bedrock-stdhub#1]
As is mentioned in README, users still have to manually enable beta APIs. This is because when I tried to make this application automatically patch `level.dat`, the patched file turned out to be replaced with an 'unpatched' version when the BDS instance started. In short, `level.dat` just gets mysteriously 'unpatched'.

The reason is currently unclear.

**Comment by Chrise2024** [comment]
Try to patch `level.dat_old` together with `level.dat`.

**Comment by Wesley-Young** [comment]
> Try to patch `level.dat_old` together with `level.dat`. Minecraft will check `level.dat` with its backup, `level.dat_old` and sync with it.

Still unable to patch. My implementation is here:
```typescript
async function main(){
  const levelDatPath = path.join(levelRoot, 'level.dat');
  const levelDatOldPath = path.join(levelRoot, 'level.dat_old');
  const levelDatBackupPath = path.join(levelRoot, 'level.dat.bak');
  fs.copyFileSync(levelDatPath, levelDatBackupPath);
  const { parsed: levelDat, type: levelDatType } = await nbt.parse(fs.readFileSync(levelDatPath));
  const experimentDataNodeOrNull = levelDat.value['experiments'];
  if (!experimentDataNodeOrNull) {
    levelDat.value['experiments'] = nbt.comp({
      experiments_ever_used: nbt.byte(1),
      gametest: nbt.byte(1),
      saved_with_toggled_experiments: nbt.byte(1),
    });
  } else {
    const experimentDataNode = <Tags[TagType.Compound]> experimentDataNodeOrNull;
    experimentDataNode.value['experiments_ever_used'] = nbt.byte(1);
    experimentDataNode.value['gametest'] = nbt.byte(1);
    experimentDataNode.value['saved_with_toggled_experiments'] = nbt.byte(1);
  }
  fs.writeFileSync(levelDatPath, nbt.writeUncompressed(levelDat, levelDatType));
  fs.writeFileSync(levelDatOldPath, nbt.writeUncompressed(levelDat, levelDatType));
  console.log('Successfully patched `level.dat`.');
  // ... more
}
```
You see, both `level.dat` and `level.dat_old` is patched. But when the server starts, it just prints
```
[2024-07-04 18:21:57:561] [bds] ERROR: [Scripting] Plugin [demo - 0.3.0] - requesting dependency on beta APIs [@minecraft/server - 1.12.0-beta], but the Beta APIs experiment is not enabled.
[2024-07-04 18:21:57:575] [bds]
[2024-07-04 18:21:57:561] [bds] ERROR: [Scripting] Plugin [demo - 0.3.0] - requesting dependency on beta APIs [@minecraft/server-net - 1.0.0-beta], but the Beta APIs experiment is not enabled.
[2024-07-04 18:21:57:576] [bds]
[2024-07-04 18:21:57:561] [bds] ERROR: [Scripting] Plugin [demo - 0.3.0] - requesting dependency on beta APIs [@minecraft/server-admin - 1.0.0-beta], but the Beta APIs experiment is not enabled.
[2024-07-04 18:21:57:576] [bds]
```
This indicates that the file is NOT successfully patched. I guess this may have something to do with files in the `db` folders like `Bedrock level/db/000016.ldb`. But which format is this file and how does it 'tell' the BDS instance that `level.dat` is modified unexpectedly?

**Comment by Wesley-Young** [comment]
Update: solved. The binary data generated by `prismarine-nbt` lacks a 8-byte-long header, which is explained [here](https://minecraft.wiki/w/Bedrock_Edition_level_format#level.dat). At the same time, a `level.dat` file generated by [NBTStudio](https://github.com/tryashtar/nbt-studio) can function as expected. It contains a header
```
[ 0x08, 0x00, 0x00, 0x00, 0x2A, 0x0B, 0x00, 0x00 ]
```
that is **different** from what is generated by BDS. I added this in front of `prismarine-nbt`-generated bytes and resulted in a right `level.dat`. By contrast, when I use the original header as the header of the generated file, it cannot function. So weird! I still do not know the reason behind this.

But at least the problem is solved.
